version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web3-gateway
    ports:
      - "2001:2001"
    environment:
      - ALCHEMY_API_KEY=H6h0lVVkm5UOG8FxuVGpWxjaIolDH_F1
      - CONTRACT_OWNER_PRIVATE_KEY=d07883be961831b1b1e0df954a95fa94e9968fd416bce23340bfcc7857cdb142
      - CONTRACT_OWNER_ADDRESS=0x17a8dD0d3199ae2c59dC96578a6B5bEFAF963db3
      - TOKEN_MINT_CONTRACT_ADDRESS=0x1293d541e381b65FdDA043eA48Eafe7098FA02b3
      - TRANSFER_TOKEN_EVENT_TBS_ENDPOINT=http://token-bridge-server:1001/tokenmint/server/internal/eventlistener/transferevent
      - CONTRACT_ABI_GITHUB_URL=https://raw.githubusercontent.com/VaishnavShelke/smart-contract-abis/refs/heads/main/0x1293d541e381b65FdDA043eA48Eafe7098FA02b3_tokenbank01.json
    networks:
      - tokenmint-ecosystem
    restart: unless-stopped

networks:
  tokenmint-ecosystem:
    external: true