const STATUS_CODE_SUCCESS = "000";
const STATUS_CODE_INVALID_FIELD = "001";
const ACCOUNT_VERIFICATION_FAILED = "002";
const INTERNAL_SERVER_ERROR = "003";

module.exports = {
  STATUS_CODE_SUCCESS,
  STATUS_CODE_INVALID_FIELD,
  ACCOUNT_VERIFICATION_FAILED,
  INTERNAL_SERVER_ERROR,
};
